# Run this job on pushes to `main`, and for pull requests.
name: main

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  # Only run one at a time per PR or branch, cancelling old jobs.
  group: ${{ github.workflow }}-${{ github.ref || github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            tests/test_requirements.txt

      - run: pip install -r requirements.txt -r tests/test_requirements.txt

      - name: Run tests
        run: PYTHONPATH=. pytest -vvv tests
